### ISSUE TITLE
summary-panel renders inconsistently

### ISSUE THREAD

**Issue by throck** [newrelic/nr1-top#10]
The summary-panel renders inconsistently, when switching between processes.  To be more specific, the panel renders on initial load, but then may not render at all when switching between processes

## Description

The summary-panel (top-right, which includes the commandName, commandLine and parent/child process id's) will occasionally not render when selecting a new process, or after re-selecting a process which had been previously selected and for which the panel previously rendered.

## Steps to Reproduce

1) In NR1, locate a host, and load the Top nerdlet.  Select a process other than the one currently selected at load, re-select the original process. The summary panel does not render.

2) In NR1, locate a host, and load the Top nerdlet.  Select a process other than the one currently selected at load, then select another.  After several selections, the summary panel no longer renders.  Note, navigating using the child/parent link yields the same result.

## Expected Behaviour

The summary-panel should load consistently, for every process

## Your Environment

* Versions 0.1.5, 0.1.6
* Browsers: 
Chrome Version 77.0.3865.120 (Official Build) (64-bit) (Mac)
Firefox 69.0.3 (64-bit) (Mac)

**Comment by tangollama** [comment]
@throck I can confirm that I was able to reproduce. I'll look into addressing this in the weeks ahead. Thanks for reporting it.
