### ISSUE TITLE
Implement more user-friend empty state

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-top#15]
## Summary

Empty state is blank. Implement the nr1-community component

**Comment by danielgolden** [comment]
I'm not confident of my description of why nothing is being displayed. Is this true?

> ### No entity found
> This Nerdpack must be run on a monitored host with the New Relic Infrastructure agent delployed on it. Please select a host that meets that criteria.


Screenshot
<img width="949" alt="Captura de Pantalla 2020-01-29 a la(s) 7 07 57 a  m" src="https://user-images.githubusercontent.com/812989/73355432-2569a780-4266-11ea-93d1-2c4a8ee8dacc.png">
