### ISSUE TITLE
Summary panel header disappears when window is resized

### ISSUE THREAD

**Issue by danielgolden** [newrelic/nr1-top#17]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
The content at the top of the right column `<div class="summary-panel">...</div>` disappears when you resize your browser window.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
1. In the Entity Explorer, select a host in the  that has New Relic Infrastructure agent to be delployed on it (try host-tower-austin for example).
2. Select "Top" from the left sidebar
3. After Top has loaded it's content, watch the top of the right column and resize your browser window.
4. `<div class="summary-panel">...</div>` will disappear 

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour
I expect that the summary panel would remain visible when I resize my window.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output
No relevant console output :/

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: @datanerd/nr1/1.10.10
* Browser name and version: Firefox 72.0.2 & Chrome 79.0.3945.130
* Operating System and version: MacOS Catalina 10.15.2

## Extra notes
May be related to #10, but I don't think it's the same. Likely a similar or the same cause, but different effect.

**Comment by tangollama** [comment]
@danielgolden I can't seem to reproduce this. Can you verify or close please?

**Comment by danielgolden** [comment]
@tangollama I can't reproduce this anymore either. Going to go ahead and close it.
