### ISSUE TITLE
View Full Command Output

### ISSUE THREAD

**Issue by Trevor-Bond** [newrelic/nr1-top#30]
## Summary

Would it be possible to show the full commands that are listed in the "Command" column? 

## Additional context

We use a lot of different parameters in our environment, and it would help if we could view the full command the process is using.

**Comment by artuone83** [comment]
I will take care of that.

**Comment by tangollama** [comment]
@Trevor-Bond re: your enhancement request. 

Thanks to @artuone83's PR, this issue should land in the app soon and you (and everyone else) should benefit from it via the New Relic One Catalog by the end of the week.
