### ISSUE TITLE
Unable to see application in NR One overview page

### ISSUE THREAD

**Issue by pholdings** [newrelic/nr1-top#8]
Hi

I just read the announcement about these NR1 apps and followed the instructions to successfully create a new app, start it, and see the placeholder for it in the New Relic One page.

I was also able to get this to work with the GraphQL sample app. 

When I do the same for nr1-top, there are no problems with build or start, but there is no entry for "top" in New Relic One.

Grateful for any help, thanks.

**Comment by tangollama** [comment]
@pholdings you need to navigate to Top in the Entity Explorer > choose a Host

You’ll see Top in the left hand nav. Also, we have a discussion thread for these types of support questions. Cheers. 

https://discuss.newrelic.com/t/new-relic-one-top-nerdpack/82934
