### ISSUE TITLE
App not visible in New Relic ONE when locally served or published

### ISSUE THREAD

**Issue by xrismck** [newrelic/nr1-top#9]
I followed the steps provided for installation and am able to get the app built, published, deployed and subscribed to.

I have followed the same method for other apps and they do display from local server and when published. (e.g. nr1-groundskeeper, nr1-container-explorer, nr1-neon)

I have experienced the same issues with:  nr1-browser-analyzer
---------------------------------------------------------------------------------------------

OUTPUT:   nr1 nerdpack:info --verbose

init version: @oclif/command@1.5.19 argv: [ '--verbose', [length]: 1 ]
Fetching info from registry...
Request: POST https://artifact-registry.service.newrelic.com/graphql
Data: 'query {\n                package(uuid: ' +
  '"f4147f2d-7c86-47d6-98df-b7a15cf00a85") {\n               ' +
  '     uuid\n                    accountId\n                 ' +
  '   publications {\n                        createdAt\n     ' +
  '                   createdByUser\n                        ' +
  'version\n                    }\n                }\n         ' +
  '       packageDeployments(uuid: ' +
  '"f4147f2d-7c86-47d6-98df-b7a15cf00a85") {\n               ' +
  '     channel\n                    deployedPublication {\n  ' +
  '                      version\n                    }\n     ' +
  '           }\n            }'
Headers: {
  'API-Key': '<my api key>',
  'Content-Type': 'application/graphql'
}

Registry: Present
Id: f4147f2d-7c86-47d6-98df-b7a15cf00a85
Region: us
Account ID: 1847652
Local version: 0.1.5

Version   Date           Deployed to channel
0.1.5     14 minutes ago DEV

---------------------------------------------------------------------------------------------
LOCAL SERVER EXECUTION
STEP:	Install
npm install

STEP:	Run locally
npm start

STEP:	Test
https://one.newrelic.com/?nerdpacks=local

RESULT:	App Not Displayed
---------------------------------------------------------------------------------------------
PUBLISH TO NEW RELIC ONE

STEP:	Create a new UUID
nr1 nerdpack:uuid -gf
Generated id is f4147f2d-7c86-47d6-98df-b7a15cf00a85

STEP:	Force publish, override version if exists
nr1 nerdpack:publish -f 

STEP:	Deploy to DEV
nr1 nerdpack:deploy --channel=DEV

STEP:	Subscribe to DEV
nr1 nerdpack:subscribe --channel=DEV

STEP:	Check info
nr1 nerdpack:info --verbose

Version   Date           Deployed to channel
0.1.5     4 minutes ago  DEV

RESULT:  App Not Displayed
---------------------------------------------------------------------------------------------

What additional information should I provide to help with troubleshooting?

**Comment by tangollama** [comment]
Chris, did you navigate to an Infra host in the entity explorer? That’s where top shows up.
